# jenkins-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Change nodePort if needed
