apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-all-permissions-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-all-permissions  # Ensure this matches the ClusterRole name
  apiGroup: rbac.authorization.k8s.io
